[tool.poetry]
name = "trudoku"
version = "0.1.0"
description = ""
authors = ["rozab"]

[tool.poetry.dependencies]
python = "^3.8"
blessed = "^1.17.4"
numpy = "^1.18.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
